version: '3.9'
services:
  xui:
    image: Mohammad084/x-ui
    container_name: x-ui
    volumes:
      - $PWD/db/:/etc/x-ui/
      - $PWD/cert/:/root/cert/
    restart: unless-stopped
    ports:
      - 54321:54321
      - 443:443
